[workspace] 
members = [
    "crates/sml-driver",
    "crates/sml-core",
    "crates/sml-frontend",
    "crates/sml-util",
]


[profile.release]
debug = false
opt-level = 3
debug-assertions = false
lto = "fat"
codegen-units = 1